# Generated by Django 6.0.5 on 2026-05-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_explanation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'text')},
        ),
    ]
